In [1]:
import sys
from pathlib import Path
import pandas as pd

sys.path.append(str(Path.cwd().parent))
import src.config as cfg
from src.data_processing import run_feature_engineering_pipeline

In [2]:
df_validated = pd.read_csv(cfg.INTERIM_DATA_DIR / "01_validated_data.csv")

In [3]:
df_engineered = run_feature_engineering_pipeline(df_validated)

In [4]:
print("--- Temperature Features ---")
display(df_engineered[['Air temperature [K]', 'Process temperature [K]', 'Temp_Difference [K]']].head(3))
print("\n--- Power Features ---")
display(df_engineered[['Rotational speed [rpm]', 'Torque [Nm]', 'Power [W]']].head(3))

print("\n--- Tool Wear Distribution ---")
display(df_engineered['Tool_Wear_Bucket'].value_counts(dropna=False))

--- Temperature Features ---

   Air temperature [K]  Process temperature [K]  Temp_Difference [K]
0                298.1                    308.6                 10.5
1                298.2                    308.7                 10.5
2                298.1                    308.5                 10.4

--- Power Features ---

   Rotational speed [rpm]  Torque [Nm]    Power [W]
0                    1551         42.8  6951.590560
1                    1408         46.3  6826.722724
2                    1498         49.4  7749.387543

--- Tool Wear Distribution ---

Tool_Wear_Bucket
New (0-60m)              2851
Operational (61-120m)    2737
Worn (121-180m)          2734
Critical (181m+)         1678
Name: count, dtype: int64

In [5]:
df_engineered.to_csv(cfg.PROCESSED_DATA_FILE, index=False)
print("\nFeature engineering complete. File saved to 03_processed.")

Feature engineering complete. File saved to 03_processed.